#            \----------------------------------------------/
#            |        Government Configuration File         |
#            |             www.Thomas.vision                |
#            /----------------------------------------------\
Settings:
  Enabled: true
Government:
  Type: 0
  Leaders: ''
