#            \----------------------------------------------/
#            |        Government Configuration File         |
#            |             www.Thomas.vision                |
#            /----------------------------------------------\
Settings:
  Enabled: true