#            \----------------------------------------------/
#            |        Government Configuration File         |
#            |             www.Thomas.vision                |
#            /----------------------------------------------\
Settings:
  Enabled: true
  VoteSoundsForSelf: true
  VoteSoundsForAll: true
  VoteTimeInSeconds: 65
  AnnounceVoteAt:
    - 120
    - 60
    - 30
    - 10
    - 5
Government:
  Type: 0
  Leaders: ''
Commands:
  Allowed: ''