#            \----------------------------------------------/
#            |        Governance Configuration File         |
#            |             www.Thomas.vision                |
#            /----------------------------------------------\
Settings:
  Enabled: true
  MinVotesRequired: 10
  PercentRequiredToPass: 66
  ChatWhileCountingVotes: false
  VoteSoundsForSelf: true
  VoteSoundsForAll: true
  VoteTimeInSeconds: 65
  AnnounceVoteAt:
    - 120
    - 60
    - 30
    - 10
Government:
  Type: 0
  Leaders: ''
  MaxLeaders: 5
  MinTermLengthInMinutes: 30
  MaxTermLengthInMinutes: 180
Commands:
  Allowed: ''