#            \----------------------------------------------/
#            |        Government Configuration File         |
#            |             www.Thomas.vision                |
#            /----------------------------------------------\
Settings:
  Enabled: true
  VoteSoundsForSelf: true
  VoteSoundsForAll: true

Government:
  Type: 0
  Leaders: ''

Commands:
  Allowed: ''