name: Government
version: ${project.version}
main: vision.thomas.government.Government
authors: [Thomas, AcpSoldier]
description: A management plugin that allows server owners to efficiently run their server by granting their players autonomy.
website: https://www.thomas.vision/portfolio/
